# Generated by Django 4.1.7 on 2023-04-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimagemodel',
            old_name='images',
            new_name='image',
        ),
    ]
