# Generated by Django 4.2 on 2023-04-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_images_carimagemodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimagemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['id']},
        ),
    ]
