# Generated by Django 4.1.7 on 2023-03-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('engine_capacity', models.FloatField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
