# Generated by Django 4.1.7 on 2023-03-24 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(40), django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=1990, validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
