# Generated by Django 4.2 on 2023-04-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparkmodel',
            options={'ordering': ['id']},
        ),
    ]
