# Generated by Django 4.1.7 on 2023-03-29 13:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,50}$', 'only letters min 2 max 50 ch')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_parks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_parks',
            },
        ),
    ]
