# Generated by Django 4.1.7 on 2023-04-01 10:33

import django.core.validators
from django.db import migrations, models

import core.services.upload_image_for_autopark


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,50}$', 'only letters min 2 max 50 ch')])),
                ('image', models.ImageField(blank=True, upload_to=core.services.upload_image_for_autopark.upload_to)),
            ],
            options={
                'db_table': 'auto_parks',
            },
        ),
    ]
